apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.service.name }}
spec:
  type: {{ .Values.deployment.service.type }}
  selector:
    app: {{ .Values.deployment.name }}
  ports:
  - protocol: {{ .Values.deployment.service.protocol }}
    port: {{ .Values.deployment.service.port }}
    targetPort: {{ .Values.deployment.service.targetPort }}
