deployment:
  name: pod-platform
  namespace: platform-eng
  image: gingerous/platform-eng
  tag: 1.1.11
  service:
    name: service-pod-platform
    type: ClusterIP
    protocol: TCP
    port: 80
    targetPort: 5000

sa:
  name: platform-sa

secret:
  namespace: default
