apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.sa.name }}-cluster-role
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["create", "delete"]

- apiGroups: [""]
  resources: ["pods","services", "secrets", "configmaps"]
  verbs: ["get", "create", "update","patch", "list"]

- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "create", "update", "patch", "list"]

- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "create", "update", "patch", "list"]

- apiGroups: ["external-secrets.io"]
  resources: ["externalsecrets", "secretstores"]
  verbs: ["get", "create", "update", "patch"]

# MongoDB
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["get", "create", "list", "watch", "patch"]

- apiGroups: ["policy"]
  resources: ["poddisruptionbudgets"]
  verbs: ["get", "list", "create", "watch", "patch"]

- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["get", "list", "create", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.sa.name }}-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.sa.name }}-cluster-role
subjects:
- kind: ServiceAccount
  name: {{ .Values.sa.name }}
  namespace: {{ .Values.deployment.namespace }}
